### ISSUE TITLE
[bug] - Recorder doesnt let me select the tab where cubecubed is running

### ISSUE THREAD

**Issue by kaptsanovb** [imaphatduc/cubecubed#15]
**Describe the bug**
When I run my scene in "http://localhost:5173/", the browser asks me to select a tab to record, but doesnt show "http://localhost:5173/".

**To Reproduce**
I added the recorder:
```
import { Recorder} from "cubecubed";
function drawShapes() {
    const recorder = new Recorder(scene);
    recorder.start();

    // rest of the example code in drawShapes()

    return scene.sceneElapsed;
}
drawShapes();
```
to the example (example.js) that came with "npx ccw"

**Your browser**
I tried Chrome and Edge

**Can you make a guess?**
No idea

**Expected behavior**
To let me record my scene. Would it be possible to just export as video without having to record the screen?

**Screenshots**
![image](https://github.com/imaphatduc/cubecubed/assets/96661993/71b677c9-273f-4605-93ae-362585115a64)

**Comment by imaphatduc** [comment]
@kaptsanovb Your issue is referenced in the latest commit. Please see the full description of the commit for better understanding of recorder's new strategy when interacting with code and the browser.

As for your mentioned feature of exporting the video without recording the browser tab, I can think of one solution which is using headless browsers such as the one Puppeteer.js provides. I have not planned this but it's a nice thing to have in the near future. If you would, can you open a PR for this one?
